/* eslint-env node */
// NOTE: This file is run pre build and creates `app.components.js`.
const { createComponentsFile } = require("../../../codegen/index");
const path = require("path");

const disclaimers = [
  "// NOTE: Do not edit this file. It is built by running `/codegen/components.js`",
  "// NOTE: The imported/exported components are exposed to the global scope"
].join("\n");

const sourcePath = path.join(__dirname, "..", "src");

createComponentsFile({
  fileHeader: disclaimers,
  fileName: "app.components.tsx",
  outputPath: sourcePath,
  searchPath: path.join(sourcePath, "components"),
  fileExtension: ".tsx",
  prettierOptions: null
});
