/* eslint-env node */
// NOTE: This file is run pre build and creates files needed to build the static site.
const path = require("path");
const { createPagesFile, createPathsFile } = require("../../../codegen/index");

const disclaimers = [
  "// NOTE: Do not edit this file. It is built by running `/codegen/pages.js`"
].join("\n");

const staticSitePath = path.join(__dirname, "..", "src", "static-site");

const commonOptions = {
  searchPath: path.join(staticSitePath, "pages"),
  fileHeader: disclaimers,
  outputPath: staticSitePath,
  fileExtension: ".tsx"
};

createPagesFile(Object.assign({}, commonOptions, { fileName: "pages.tsx" }));
createPathsFile(Object.assign({}, commonOptions, { fileName: "paths.tsx" }));
