// NOTE: Do not edit this file. It is built by running `/codegen/components.js`
// NOTE: The imported/exported components are exposed to the global scope

import Header from "./components/Header/Header";

export { Header };
