// NOTE: Do not edit this file. It is built by running `/codegen/pages.js`

import PageIndex from "./pages/page-index/page-index";
import TestSite from "./pages/test-site/test-site";

export default [
  {
    component: PageIndex,
    group: "",
    name: "Page Index",
    path: "/"
  },
  {
    component: TestSite,
    group: "",
    name: "TestSite",
    path: "/test-site"
  }
];
