// NOTE: Do not edit this file. It is built by running `/codegen/pages.js`

import { HeaderPage } from "./pages/header-page/header-page";
import { PageIndex } from "./pages/page-index/page-index";

export default [
  {
    component: HeaderPage,
    group: "",
    name: "HeaderPage",
    path: "/header-page"
  },
  {
    component: PageIndex,
    group: "",
    name: "Page Index",
    path: "/"
  }
];
